name: vertical
description: 'Simple vertical calendar for better clarity.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  image_path: 'assets/icon/logo.png'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
  # Add assets from the images directory to the application.
  # - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKr-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKr-Medium.ttf
          weight: 400
